services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./erp_backend:/project/erp_backend
      - ./base:/project/base
      - ./manage.py:/project/manage.py
      - ./pyproject.toml:/project/pyproject.toml
      - ./pdm.lock:/project/pdm.lock
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    command: ["pdm", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
