services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
