services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/project
      - /dev/null:/project/.pdm-python
      - /project/.venv

    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    command: ["sh", "/project/entrypoint.sh"]

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
